name: fishclicker
description: A simple StageXL web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: nick-newman <44561033+nick-newman@users.noreply.github.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  stagexl: ^1.4.0

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
